[mysql]
url = "jdbc:mysql://192.168.30.100:3306/demo1?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true"
username = "demo1"
password = "watsEpkS6P8fwcAw"
driver = "com.mysql.cj.jdbc.Driver"


[pgsql]
url = "jdbc:postgresql://192.168.30.100:5432/demo1
username = "demo1"
password = "MpmeKNHdaAKR4yyR"
driver = "org.postgresql.Driver"
